language: python

python:
  - "3.5"
  - "3.6"

install: 
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - pip install -e .

script: 
  - python -m nose --with-coverage --cover-package=EEHlib --cover-package=EEH
